package com.example.hotels.enums;

public enum ErrorType {

    NO_ACTIVE_CUSTOMER,
    NO_ACTIVE_ROOM_WITH_ID,
    IF_CANCELLED_SET_A_NOTE,
    NO_ACTIVE_ROOM_IN_SELECTED_DATES,

    SELECTED_CUSTOMER_IS_IN_BLACKLIST

}
